<?php
namespace app\controllers;

use app\models\UserAdvertisement;
use yii\base\Action;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * Мои объявления
 *
 * Class MyAdvertisementController
 *
 * @package app\controllers
 */
class MyAdvertisementController extends BaseController
{
    /**
     * Получить имя модели
     *
     * @return string
     */
    protected function getModelName(): string
    {
        return UserAdvertisement::class;
    }

    /**
     * Смена статуса
     *
     * @param int $id id записи
     * @param int $status статус
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionSetStatus(int $id, int $status)
    {
        $model = $this->findModel($id);
        $model->statusId = $status;
        if ($model->save()) {
            \Yii::$app->session->setFlash('success', "Объявление успешно закрыто");
            return $this->redirect(['index', 'id' => $model->id]);
        }
    }

    /**
     * Запрет над действиями записей
     *
     * @param Action $action экшн
     *
     * @return bool
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $user = \Yii::$app->user->identity;
        if ($user && $action->id == 'create' && $user->isEmptyProfile()) {
            throw new ForbiddenHttpException('У вас не заполнен профиль,пожалуйтса, заполните его');
        }
        $actions = ['update', 'delete', 'set-status'];
        $id = \Yii::$app->request->get('id');
        if (!empty($id) && in_array($action->id, $actions)) {
            $model = $this->getModel($id);
            if ($model->userId !== $user->id) {
                throw new ForbiddenHttpException('У вас нет прав на действия с этой записью');
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
